language: java
jdk: openjdk8
branchs.only: master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"

script:
  - cd bookup-api
  - "./gradlew clean build -x test"
  - cd ../bookup-front
  - npm install
  - npm run build

before_deploy:
  - cd ../deploy
  - openssl aes-256-cbc -K $encrypted_71566cf63c17_key -iv $encrypted_71566cf63c17_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 0400 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  script: "./deploy.sh"

notifications:
  slack:
    rooms:
      secure: C0hT62Z9XDUQ9mqWmKYPVICIZTxkvwx9ID61jAiFpXppMB0uO62C/LnsGAdTZMkt3AlBov/Sm5Ap4KxVbX6ffFhVB5BNnUNUOg0+yZ0gBFtIsvtdfWOCOIeCpF/yOQhizUAXfHmK8uAnI8zvToDUS7qNwzh7gui9poLvBI4ZPFehfC584xOL9bpI3n3rk16jJ69amYv5+pW9U/jS+33dOifvJk01NAWQTb44PmN49ktKIwyknTnsikIMOXenWjAWJL63iE3AGjXrf+WSkvBUo8NAL26TnJ2LMxz3hvAF3NyCl1/qiYEWXP9u4X0tO96R3gfro1bscUd8xQ46J9rMJuT5t3RAFkLuf/joHpjdUUAv8P7Qmli0J04Jpm9E7ykQZXtRkYAfId3INP8H4fak54SD4mvCBZlRQ2RoNrAfbvV69FeU9jO0ZDj8sCwe7tqixytujhmrSC7vafT2cGB7WiaL9DN7/HZJIbfkn0pES829jLrSiS6SGJirh7NyOdJ0fpidjJDLJcNYK1Dce2qMZ6rER9lLtp3pAqUrXoptninunzf4psIx14tvmku7T/K+OzDFkydUdgzbKSezikadxBL6gLFxHPEBBIjLA5d7lX3jmFp2DJbKZmyOdapEJk699rdRlQfvIhd7lhpDa1zC8IhB6HmEur82Z5feWRFDibo=
    on_success: always
    on_failure: always
