bookup:
  crawler:
    aladin.url: "http://www.aladin.co.kr/search/wsearchresult.aspx?SearchTarget=UsedStore&SearchWord=%s"
  rest:
    naver.url: "https://openapi.naver.com/v1/search/book.json?query=%s"
    kyobo:
      url: "http://mkiosk.kyobobook.co.kr/kiosk/product/ajaxOtherStockQty.ink?site=&ejkGb=KOR&barcode=%s"
      storeUrl: "http://mkiosk.kyobobook.co.kr/kiosk/search/searchMain.ink?site=%s&isbn=%s"